"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "app/components/Header/Header";
import "app/sass/globals.sass";
import { StepsProvider } from "app/context/stepsContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StepsProvider>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </StepsProvider>
    </html>
  );
}
